version: '3'
services:
  scrapper:
    image: scrapper
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    ports:
      - 27017:27017